
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author programmer
 */
public class FileManipulationGUI extends javax.swing.JFrame {

    /**
     * Creates new form FileManipulationGUI
     */
    public FileManipulationGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jxtView = new javax.swing.JTextArea();
        btnWriteText = new javax.swing.JButton();
        btnReadText = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jxtView2 = new javax.swing.JTextArea();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jxtView.setColumns(20);
        jxtView.setRows(5);
        jScrollPane1.setViewportView(jxtView);

        btnWriteText.setText("Write Text");
        btnWriteText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWriteTextActionPerformed(evt);
            }
        });

        btnReadText.setText("Read Text");
        btnReadText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadTextActionPerformed(evt);
            }
        });

        jxtView2.setColumns(20);
        jxtView2.setRows(5);
        jScrollPane2.setViewportView(jxtView2);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnWriteText)
                                .addGap(33, 33, 33)
                                .addComponent(btnReadText))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(42, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWriteText)
                    .addComponent(btnReadText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnClose)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnWriteTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWriteTextActionPerformed
        FileWriter writer = null;
        BufferedWriter buffWriter = null;
        //declare a file 
        File file = new File("C:\\Users\\programmer\\Desktop\\VARSITY COLLEGE\\myNewFile.txt");       
        //check if file exists        
        if(file.exists())
            JOptionPane.showMessageDialog(null,"File already exists");
        try {
            writer = new FileWriter(file, true);
            buffWriter = new BufferedWriter(writer);            
        }catch (IOException ex) {
            System.out.println("File Error"+ ex); 
        }        
        try {
            buffWriter.write(jxtView.getText()); 
            buffWriter.newLine(); 
            jxtView.setText("");
            jxtView.requestFocus();
        } catch (IOException ex) {
            System.out.println("Write error: "+ex);
        }
        try {
            buffWriter.flush();
//        try {
//            buffWriter.close();
//            writer.close();
//        } catch (IOException ex) {
//            Logger.getLogger(FileManipulationGUI.class.getName()).log(Level.SEVERE, null, ex);
//        }
        } catch (IOException ex) {
            Logger.getLogger(FileManipulationGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnWriteTextActionPerformed

    private void btnReadTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadTextActionPerformed
         FileReader file = null;
        try {
            file = new FileReader("C:\\Users\\programmer\\Desktop\\VARSITY COLLEGE\\myNewFile.txt");
        }catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"File Opening error");
        }
        BufferedReader buff = new BufferedReader(file);
        String text = "";
        String line;
        try {
            line = buff.readLine();
            while(line!= null){
                text = text + line +"\n"; 
                line = buff.readLine();
            }        
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null,"File Read error");
        }
        jxtView.setText(text);
    }//GEN-LAST:event_btnReadTextActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        JOptionPane.showMessageDialog(null,"You want to close???");
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileManipulationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileManipulationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileManipulationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileManipulationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileManipulationGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReadText;
    private javax.swing.JButton btnWriteText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jxtView;
    private javax.swing.JTextArea jxtView2;
    // End of variables declaration//GEN-END:variables
}
