/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ATM;

import javax.swing.JOptionPane;

/**
 *
 * @author programmer
 */
public class ATM extends javax.swing.JFrame {
    static int balance = 800;
    /**
     * Creates new form ATM
     */
    public ATM() {
        initComponents();
        btnOK.setEnabled(false);// disable the OK button
        cboWithdraw.setSelectedIndex(-1); // select no option in the combobox
        cboWithdraw.setEnabled(false);//disable the combobox
        txtDepAmount.setEnabled(false);//disable the amount textfield
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionsGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        chkBal = new javax.swing.JCheckBox();
        lblBal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        chkWithdraw = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cboWithdraw = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        chkDep = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        txtDepAmount = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        optionsGroup.add(chkBal);
        chkBal.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        chkBal.setText("Balance");
        chkBal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkBalItemStateChanged(evt);
            }
        });
        chkBal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBalActionPerformed(evt);
            }
        });

        lblBal.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        lblBal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Available Balance");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkBal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblBal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkBal)
                    .addComponent(lblBal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        optionsGroup.add(chkWithdraw);
        chkWithdraw.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        chkWithdraw.setText("Withdrawal");
        chkWithdraw.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkWithdrawItemStateChanged(evt);
            }
        });
        chkWithdraw.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                chkWithdrawPropertyChange(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Select Withdrawal Amount");

        cboWithdraw.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "100", "1000" }));
        cboWithdraw.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboWithdrawItemStateChanged(evt);
            }
        });

        jLabel4.setText("R");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(chkWithdraw)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkWithdraw)
                    .addComponent(cboWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(15, 15, 15))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        optionsGroup.add(chkDep);
        chkDep.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        chkDep.setText("Deposit");
        chkDep.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkDepItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Enter Deposit Amount");

        txtDepAmount.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkDep, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDepAmount))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkDep)
                    .addComponent(txtDepAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        btnOK.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnCancel))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        if(chkWithdraw.isSelected()){
            balance = balance - Integer.parseInt(cboWithdraw.getSelectedItem().toString());
            lblBal.setText("R"+String.valueOf(balance));//set the lblBal label string to be the balance
            JOptionPane.showMessageDialog(null,"Withrawal of + R"+Integer.parseInt(cboWithdraw.getSelectedItem().toString())+" is successful.");
            //diactivate the controls
            btnOK.setEnabled(false);// disable the OK button            
            optionsGroup.clearSelection();// reset so none of the checkboxes are selected
            cboWithdraw.setSelectedIndex(-1); // select no option
            cboWithdraw.setEnabled(false);//disable the combobox
        }
        if(chkDep.isSelected()){ 
           int amount = Integer.parseInt(txtDepAmount.getText());// read deposit amount from textbox 
           //check if amount is great than zero and amount is in multiples of 10 e.g. 10, 20,30,40 etc
           if(amount>0 && amount%10==0){
               balance = balance + amount;
               lblBal.setText("R"+String.valueOf(balance));//set the lblBal label string to be the balance 
                //diactivate the controls
                btnOK.setEnabled(false);// disable the OK button            
                optionsGroup.clearSelection();// reset so none of the checkboxes are selected
                cboWithdraw.setSelectedIndex(-1); // select no option
                cboWithdraw.setEnabled(false);//disable the combobox
                txtDepAmount.setEnabled(false);//disable the amount textfield
                txtDepAmount.setText("");//clear text in text field
                JOptionPane.showMessageDialog(null,"Deposit of R"+amount+" is successful.");
            }else{
               JOptionPane.showMessageDialog(null,"Enter an amount greater than ZERO and a multiple of R10.");
           }
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void chkBalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBalActionPerformed

    private void chkBalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkBalItemStateChanged
        btnOK.setEnabled(false);// disable the OK button
        cboWithdraw.setSelectedIndex(-1); // select no option
        cboWithdraw.setEnabled(false);//disable the combobox
        txtDepAmount.setEnabled(false);//disable the amount textfield
        txtDepAmount.setText("");//clear text in text field
        lblBal.setText("R"+String.valueOf(balance));//set the lblBal label string to be the balance
    }//GEN-LAST:event_chkBalItemStateChanged

    private void chkWithdrawPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_chkWithdrawPropertyChange
           
    }//GEN-LAST:event_chkWithdrawPropertyChange

    private void chkWithdrawItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkWithdrawItemStateChanged
         lblBal.setText("R"+String.valueOf(balance));//set the lblBal label string to be the balance
         cboWithdraw.setEnabled(true);//disable the combobox
         txtDepAmount.setEnabled(false);//disable the amount textfield
          txtDepAmount.setText("");
    }//GEN-LAST:event_chkWithdrawItemStateChanged

    private void cboWithdrawItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboWithdrawItemStateChanged
       
        if(cboWithdraw.getSelectedIndex()!=-1){ // if the user has selected the amount to withdraw
            if(Integer.parseInt(cboWithdraw.getSelectedItem().toString())<=balance)  //if amount selected in the combo box is less than equal to the balance
                btnOK.setEnabled(true);// Enable the OK button
            else{
                btnOK.setEnabled(false);//disable the OK button and show message below
                JOptionPane.showMessageDialog(null,"Amount to withdraw must be less than the balance : R"+balance);
            }
         }
    }//GEN-LAST:event_cboWithdrawItemStateChanged

    private void chkDepItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkDepItemStateChanged
        btnOK.setEnabled(true);// disable the OK button
        cboWithdraw.setSelectedIndex(-1); // select no option
        lblBal.setText("R"+String.valueOf(balance));//set the lblBal label string to be the balance cboWithdraw.setSelectedIndex(-1); // select no option
        txtDepAmount.setEnabled(true);//enable the amount textfield
        cboWithdraw.setEnabled(false);//disable the combobox
        cboWithdraw.setEnabled(false);//disable the combobox
        
    }//GEN-LAST:event_chkDepItemStateChanged

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox cboWithdraw;
    private javax.swing.JCheckBox chkBal;
    private javax.swing.JCheckBox chkDep;
    private javax.swing.JCheckBox chkWithdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBal;
    private javax.swing.ButtonGroup optionsGroup;
    private javax.swing.JTextField txtDepAmount;
    // End of variables declaration//GEN-END:variables
}
